### PR TITLE
A collection of icons used for design documents including NSX-T VMware components

### PR DESCRIPTION
**Pull request by novakkkarel**

### CODE REVIEW

**Comment by ad1992** [comment]
@novakkkarel  I have updated the PR, let me know if it's fine now. You can try at https://excalidraw-libraries-git-fork-novakkkarel-main-excalidraw.vercel.app/?theme=light&sort=default

**Comment by novakkkarel** [comment]
Great! All is good thanks

On 20 June 2021 at 15:14:39, Aakansha Doshi ***@***.***)
wrote:

@novakkkarel <https://github.com/novakkkarel> I have updated the PR, let me
know if it's fine now. You can try at
https://excalidraw-libraries-git-fork-novakkkarel-main-excalidraw.vercel.app/?theme=light&sort=default

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/excalidraw/excalidraw-libraries/pull/141#issuecomment-864553279>,
or unsubscribe

**Comment by dwelle** [comment]
Let's use light theme png.

**Comment by dwelle** [comment]
I'd also use lighter background on some of the elements so they're more readable:

https://excalidraw.com/?#json=5146197069135872,pTyWrwVu2-gQ_YahjvqZrw

image

**Comment by novakkkarel** [comment]
Hi so this is better ?


On 20 June 2021 at 15:23:55, David Luzar ***@***.***) wrote:

I'd also use lighter background on some of the elements so they're more
readable:

https://excalidraw.com/?#json=5146197069135872,pTyWrwVu2-gQ_YahjvqZrw

[image: image]
<https://user-images.githubusercontent.com/5153846/122675827-7c657900-d1db-11eb-92b6-d086ddb418a8.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/excalidraw/excalidraw-libraries/pull/141#issuecomment-864554632>,
or unsubscribe

**Comment by novakkkarel** [comment]
I upload light version so can you approve now? thanks


On 20 June 2021 at 15:14:39, Aakansha Doshi ***@***.***)
wrote:

@novakkkarel <https://github.com/novakkkarel> I have updated the PR, let me
know if it's fine now. You can try at
https://excalidraw-libraries-git-fork-novakkkarel-main-excalidraw.vercel.app/?theme=light&sort=default

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/excalidraw/excalidraw-libraries/pull/141#issuecomment-864553279>,
or unsubscribe

**Comment by dwelle** [comment]
It seems the new png * excalidrawlib files have different names than the previous ones.

**Comment by novakkkarel** [comment]
I updated now in json

-- 
Karel Novak

**Comment by dwelle** [comment]
Merging. Thanks!

**Pull request merged**
