### PR TITLE
adding some bad-maps

### PR DESCRIPTION
**Pull request by robertdean**

### CODE REVIEW

**Comment by dwelle** [comment]
I don't think they're bad at all.

The only thing that's bad about them is the performance when you drop the whole world, but that's on us :).

Btw, Chile, and some countries in Africa and Indonesia don't seem to be closed so they're unfilled (it may have happened during resize). Otherwise :+1:

**Comment by robertdean** [comment]
I see the issue with the World Map. I was working on a M1 Mac mini and didn't see any performance degradation. Then I moved to my Intel MacBook and it was grinding to a halt. I will break up the world into continents and see if that makes it a bit easier to work with.

**Comment by dwelle** [comment]
Btw, I noticed you probably used the freedraw tool, which is why you ended up we a ton of points adding up to the bad performance.

For comparison, here's low-poly US & Africa maps I did once: https://excalidraw.com/#json=4827613830840320,1v8APpLh0Hml2G_eTw541Q

**Review by robertdean — COMMENTED** [review]
fixed some broken country maps, removed the gigantic world map

**Comment by robertdean** [comment]
Reorganized maps. Hope this works better :)

**Comment by robertdean** [comment]
@dwelle I see your low-poly version and I like it much better. I traced these from the Wikipedia versions. Not ideal. Need to figure out how to low-poly them back to sanity.

**Comment by robertdean** [comment]
I understand if you leave this version out for performance issues. I don’t want to lock up anyone’s browser…

**Comment by dwelle** [comment]
You could in theory use the simplifier from roughJS that we're already using for lines, but with a higher factor. Probably won't help much in this case. Apart from that, my idea was to iterate through the points in triplets and remove the third point if a distance from previous is under a certain distance, provided the angle is under a certain threshold:

image

Unclear if this would work or not.

**Pull request closed without merging**
