### PR TITLE
Added html, css and js logos

### PR DESCRIPTION
**Pull request by Madhusuthanan-B**
### Added html, css and js logos

- As a user, I was missing these logos when making sketches related to front end tech. It would be nice to have them included in the library

image

### CODE REVIEW

**Comment by dwelle** [comment]
Hello. If I may offer some suggestions, instead of simple numbers I'd draw up the proper pictographic numbers that the logos use:

image

Anyway, let's make the logo library items separate. Right now there's only one item that contains all 3 logos.

**Comment by Madhusuthanan-B** [comment]
@dwelle : Thanks for the suggestions. Updated the logos in the latest commit with pictographic numbers. Please check.

They look like below below now.

image

**Comment by Madhusuthanan-B** [comment]
If the changes are fine, can we get this PR merged?

**Comment by dwelle** [comment]
Yep, sorry. Thanks for the lib!

**Pull request merged**
