### PR TITLE
Add emojis

### PR DESCRIPTION
**Pull request by anumithaapollo12**

### CODE REVIEW

**Comment by dwelle** [comment]
Hey, these look nice ❤️.

Should these be considered duplicate?

image

They differ only in the eyes which is not very perceptible.

**Comment by anumithaapollo12** [comment]
Hey thank you!
Yeah its pretty similar, I thought different eyes expression changes the emotion a bit! However I could remove it too because it is not that perceptible! What do you think?

**Comment by dwelle** [comment]
@anumithaapollo12 yeah I'd probably remove it because this tiny difference would likely be construed as an artifact of roughjs rendering, not an intention (if at all). Other than that, we can ship it!

**Comment by anumithaapollo12** [comment]
Hey I removed the 2 duplicate ones and replaced it with 2 other emojis.

Screenshot 2021-05-08 at 10 56 50 AM

**Comment by dwelle** [comment]
Thanks. Looking great! :rocket:

**Pull request merged**
