### PR TITLE
add components for system design

### PR DESCRIPTION
**Pull request by aretecode**
<details><summary>Preview</summary>

### Icons
system-design-template-emoji--small

### Analysis
system-design-template-blocks -- v2

### Prefab condition flows
system-design-template-blocks-conditionals -- v2

---

#### Modifiers and presets
_left side is included, right side is an example_

system-design-template-blocks--presets -- v2 - light

### Example

_Not included, here to show how the parts can be used_

[app.excalidraw link](https://app.excalidraw.com/s/1C24U3S2zX3/8v22Phbln3g)
system-design-template-aretecode-emoji--example

---

Ticket: https://github.com/aretecode/system-design-templates-excalidraw/issues/3

</details>

Live: https://app.excalidraw.com/l/1C24U3S2zX3/5PBVn1BngL4
Example live: https://app.excalidraw.com/l/1C24U3S2zX3/8v22Phbln3g
More: https://github.com/aretecode/system-design-templates-excalidraw

### CODE REVIEW

**Comment by ferminrp** [comment]
Hey @aretecode this looks like a collection of emojis. Is it that much different than copying and pasting from other platforms like whatsapp? What am I missing?

**Comment by aretecode** [comment]
@ferminrp 

### Emoji
Some of the emoji are 1:1 emoji, some are custom emoji.

The goal is to have components for each system design feature. Emoji is the simplest way to represent them. 

All components are title + image. They are arranged into groups according to their use case in a system design. 

You could remember all of the components, copy-paste emoji in, resize the font, create the boxes, and write the text, but that is relatively slow to do during an interview or rapid design.

### Some of the custom emoji
Screen Shot 2021-08-02 at 16 46 42


---

Some of the other components 

### Analysis
system-design-template-blocks -- v2

### Prefab condition flows
system-design-template-blocks-conditionals -- v2

**Comment by dwelle** [comment]
Hey @aretecode. This seems like too specific a use case, especially some of those items. If anything, each item should be its own library item: right now all the emojis are in a single library item which makes it hard to use.

**Comment by aretecode** [comment]
@dwelle thanks for the update. Would you prefer that I give separate PRs for the components?

**Comment by dwelle** [comment]
> thanks for the update. Would you prefer that I give separate PRs for the components?

Yeah, probably — I have not realized it also includes the conditionals etc. I think the first 2 libraries can be released together. The 3rd  is probably unrelated? I'm not sure, the 3rd and 1st could also be grouped together. You certainly have an opinion on this.

The 4th emoji library item though should be split up so that each "emoji" is its own item. That said, I'm still not sure if public libraries is a good fit for these: if we start publish a library item for emoji in existence (currently more than 3500 emojis?) that could create a lot of unnecessary clutter, especially after we support per-item searching/installing, and it also seems kinda pointless (though I'm aware some of your emoji items are composites).

**Pull request closed without merging**
