### PR TITLE
Add Software architecture library

### PR DESCRIPTION
**Pull request by YouriTjang**

### CODE REVIEW

**Comment by lipis** [comment]
Something is wrong when trying to add it: https://excalidraw-libraries-git-fork-youritjang-main.excalidraw.vercel.app/

Also could we remove the first hexagon?

**Comment by lipis** [comment]
Found the error: There is a typo in the filename of the lib :)

**Comment by YouriTjang** [comment]
Fixed the typo, thanks :) 
As for the hexagon; I use it to show a (micro) service. As opposed to a monolith, for which I use a normal rectangle. We have many of both, so from this library, I actually use the hexagon the most. The hexagon is often used by others for micro-services as well, but it's not any kind of standard.

**Comment by lipis** [comment]
Fair enough.. just though it's quite basic and the preview would be better with 6..! As you wish :)

**Comment by lipis** [comment]
Let me know when it's ready and I'll publish it..! Thanks

**Comment by YouriTjang** [comment]
All done, go ahead

**Comment by lipis** [comment]
Thanks again!

**Pull request merged**
