### PR TITLE
feat: new library Information Architecture

### PR DESCRIPTION
**Pull request by excalibot**
A visual vocabulary for describing information architecture and interaction design, by Jesse James Garrett.

Submitted by @inwardmovement

Items: page, file, flow reference, page stack, file stack, cluster, decision point, conditional branch, conditonal selector, concurrent set, continuation x, continuation y, area, iterative area, conditional area, flow area x, flow area y

[Installation link](https://excalidraw.com/?addLibrary=https%3A%2F%2Fraw.githubusercontent.com%2Fexcalidraw%2Fexcalidraw-libraries%2Finwardmovement-information-architecture%2Flibraries%2Finwardmovement%2Finformation-architecture.excalidrawlib%3Fraw%3Dtrue)

### CODE REVIEW

**Comment by inwardmovement** [comment]
Reupload/update of https://github.com/excalidraw/excalidraw-libraries/tree/main/libraries/inwardmovement

**Comment by dwelle** [comment]
@inwardmovement could you merge it (= replace the `excalidrawlib` file) into your existing library?

**Comment by inwardmovement** [comment]
@dwelle you mean by creating another PR?

**Comment by dwelle** [comment]
@inwardmovement I thought the files were separate so I wanted to merge them, but looking at it the only thing that needed merging was the `libraries.json` file metadata.

Alright, seems we're good to go. Thanks for the update!

**Pull request merged**
