### PR TITLE
Add Canvases collection

### PR DESCRIPTION
**Pull request by shellerbrand**
Working on canvases is a great use case for collaboration with excalidraw. The templates in this library can be used to kick-start the a canvas based modelling process.

### CODE REVIEW

**Comment by nrgapple** [comment]
I was thinking a better description could be helpful. Canvases could mean a lot of things

**Comment by shellerbrand** [comment]
> I was thinking a better description could be helpful. Canvases could mean a lot of things

Thanks for the feedback @nrgapple. My intention is to create a set of canvas templates that can grow over time. This commit contains the two canvases that I am primarily using at the moment. However, I intend to add more templates in the future.

Here is a suggestion for an updated description:

"A collection of templates for canvases for modelling various business aspects. The following canvases are in this collection: Business Model Canvas, Value Proposition Canvas."

Happy to hear your feedback.

**Comment by nrgapple** [comment]
The new descriptions are great!

**Comment by shellerbrand** [comment]
> The new descriptions are great!
@nrgapple 

Thanks for the feedback, Adam. Is there anything else that is needed for approval? 

If not, then I will go ahead and update this pull request to resolve the merge conflicts, so that it can be merged to master.

**Comment by lipis** [comment]
The reason we were holding on on this one, is as the we have already some canvases.. but this looks different.. 

One comment though.. maybe the Title should also a bit more specific.

**Comment by shellerbrand** [comment]
@lipis , thank you for the feedback.

> The reason we were holding on on this one, is as the we have already some canvases.. but this looks different..
> 
Is this a duplication of something you already have or is there something else called "canvas" in the project and you would rather have me call this differently to avoid confusion?

> One comment though.. maybe the Title should also a bit more specific.
How about "Business Modelling Canvas Templates" for a title?

**Comment by dwelle** [comment]
Thanks :)

**Pull request merged**
