### PR TITLE
feat: new library Football Icons

### PR DESCRIPTION
**Pull request by excalibot**
A few icons/ images I created in Excalidraw

Submitted by @PFound

Items: Footballer, Whistle, Football Boot, Scarf, Trophey, Football

[Installation link](https://excalidraw.com/?addLibrary=https%3A%2F%2Fraw.githubusercontent.com%2Fexcalidraw%2Fexcalidraw-libraries%2Fpfound-football-icons-1682006047495%2Flibraries%2Fpfound%2Ffootball-icons.excalidrawlib%3Fraw%3Dtrue)

### CODE REVIEW

**Comment by dwelle** [comment]
Nice. How about switching the shoe with this one?


image

```
{"type":"excalidraw/clipboard","elements":[{"id":"gR7LQFHo9pcIx-j-OvGRr","type":"line","x":-2983.733907711414,"y":-3724.701973672533,"width":176.50816455674112,"height":32.637358729359676,"angle":0,"strokeColor":"transparent","backgroundColor":"#2b8a3e","fillStyle":"cross-hatch","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1875834455,"version":510,"versionNonce":1739791258,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[44.18254685130978,19.315987819416932],[76.37585988367118,19.09396497091757],[121.89054382597578,14.4314851524382],[168.9593877077732,5.994616909474189],[154.30587970683564,22.868353395401755],[118.33817824999096,30.639153092868582],[78.818111217161,25.976673274388304],[43.96052400281087,21.31419345590848],[15.98564509193102,9.76900533395792],[-7.548776848967918,-1.9982056364910932]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"VD-XEVkOWL8TvMn9mBmeK","type":"line","x":-2999.4760419083323,"y":-3873.9978890567463,"width":72.43557353868573,"height":33.38070682708948,"angle":0,"strokeColor":"transparent","backgroundColor":"#2b8a3e","fillStyle":"cross-hatch","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":41281911,"version":538,"versionNonce":1747165126,"isDeleted":false,"boundElements":null,"updated":1682008210527,"link":null,"locked":false,"points":[[0,0],[-21.471130918633207,-8.372359692787532],[-50.72849612644086,-11.525586070591118],[-64.29541950909379,-9.677143021533729],[-71.25584107062878,0.4349277762492909],[-67.71664366645837,9.894606909658373],[-58.39675716880993,17.614574938073225],[-41.64455612240363,21.855120756498362],[-24.892355075997784,19.136822154943648],[-14.510709357098222,10.220802741844922],[1.1797324680569545,1.6309791609327449]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"WfBHNaYcx_X-ApGmoQXEn","type":"line","x":-3088.750715051463,"y":-3792.862988161739,"width":76.59788273217009,"height":53.063460791272064,"angle":0,"strokeColor":"transparent","backgroundColor":"#2b8a3e","fillStyle":"cross-hatch","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":350376599,"version":395,"versionNonce":1690343514,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[17.095759334426475,18.42789642542084],[58.169986306749706,41.96231836631978],[76.59788273217009,53.063460791272064],[13.099348061443834,29.751061698872036],[1.998205636491548,15.98564509193102],[1.3321370909943653,1.5541599394928198]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"oJ4CHg-MDSZCH6tM_KFOl","type":"line","x":-2998.0292200902604,"y":-3874.9855390433904,"width":116.96646900733458,"height":35.70253193785629,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"transparent","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":112261401,"version":742,"versionNonce":930558534,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[-30.05388805047778,-11.005649145245116],[-61.67779557197173,-12.421351053682884],[-71.55938143829053,-2.102307243098039],[-66.8889815150842,12.71582243246803],[-46.139067570452426,23.28118088417341],[-24.97435767574916,18.624944707338727],[-7.619295562092702,3.809647781046806],[0,0],[14.358801025696266,-5.1615261812848985],[23.598813091251486,-7.524574402594226],[34.3405122107888,-8.814295237855731],[42.31001456979402,3.9437933823228377],[45.40708756904405,12.6256097104133]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"I7_12p3lzT30z_Qc99gx2","type":"line","x":-3077.5053580366794,"y":-3870.607134892687,"width":198.86889785114226,"height":100.58645071168894,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"transparent","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":505655863,"version":803,"versionNonce":75529498,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[1.9508224297951529,15.378744940393517],[13.35993652801426,24.96585942792717],[31.84756016842084,29.210132403964963],[50.35501305374737,25.403317372193214],[70.34750293185971,19.04823890523312],[86.73281932916734,19.59752317296261],[94.94672314737863,26.51038415547373],[104.259195501048,37.5160333007193],[111.45770531671815,47.25221792752791],[128.81297646799703,60.16404970784333],[141.72083653348318,78.57494338357537],[158.43980764337448,94.02444997502971],[176.00515811143168,100.16273843855015],[191.24563057422074,100.58645071168894],[198.86889785114226,97.20385980574247],[178.97051691053775,77.09414532262554],[163.520801281461,61.218627044182995],[147.43520368624195,41.325681081766106],[133.12977919309924,24.007169657888426]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"XzyGVNDIp4tUWMFk2xvHy","type":"line","x":-2945.6416442403984,"y":-3856.4289973841887,"width":278.9508764121847,"height":187.94262386496484,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"transparent","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":399541849,"version":884,"versionNonce":1604647302,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[22.322510605320986,30.978459730014947],[52.37639865579922,59.762465186810914],[87.93311127890001,87.27658804992507],[116.71711673569644,101.24529658042911],[129.8392368704117,121.1401238814492],[133.6488846514585,130.87589043301296],[125.18300069357747,138.91848019300005],[98.09217202835725,144.844598963517],[54.492869645269366,149.07754094245774],[41.794043708448044,149.0775409424573],[26.555452584261275,152.8871887235041],[2.0043891064060517,149.92412933824562],[-33.129029318800804,132.99236142248355],[-68.6857419419016,113.09753412146256],[-112.28504432498949,92.35611842465369],[-139.37587299020925,70.34482013416255],[-145.3019917607262,52.14316962471821],[-145.30199176072574,26.32222355317799],[-141.069049781785,3.8876310647924583],[-132.60316582390396,-15.583902038334145],[-122.44410507444672,-29.129316370943798],[-109.74527913762495,-33.36225834988409],[-91.12033443028622,-35.05543514146075],[-71.64880132715962,-29.129316370943798],[-50.907385630350745,-20.240138215168827]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"LFOHyTJmp2i6Q878yMmPk","type":"line","x":-3089.9894759154686,"y":-3790.3105672594347,"width":77.28922475918398,"height":48.091073183492426,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"transparent","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":945047031,"version":341,"versionNonce":342215130,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[3.4350766559637123,16.48836794862609],[18.892921607800417,29.19815157569201],[53.243688167437995,42.251442868353934],[77.28922475918398,48.091073183492426]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"5KopmiA6YTtiKThMQGODJ","type":"line","x":-2989.6852375613275,"y":-3726.761649124105,"width":176.56294011653608,"height":31.946212900462797,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"transparent","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":254094009,"version":412,"versionNonce":622319814,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[39.15987387798668,20.953967601378736],[77.28922475918398,29.19815157569201],[120.22768295873084,31.946212900462797],[154.92195718396442,24.73255192293891],[170.03629447020512,15.457844951836705],[176.56294011653608,2.0610459935783183]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"dGbPeNIxxu_0AfZCVYuDP","type":"line","x":-3084.795078406951,"y":-3849.293310695002,"width":91.71654671423175,"height":98.24319236056272,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#2b8a3e","fillStyle":"cross-hatch","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1104659449,"version":530,"versionNonce":998473370,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[5.496122649542031,18.205906276607493],[33.32024356284819,43.96898119633579],[63.892425800925594,65.26645646331099],[76.60220942799151,66.29697946009992],[79.69377841835876,50.49562684266675],[82.09833207753309,39.50338154358269],[87.59445472707512,54.27421116422693],[88.6249777238645,75.91519409679859],[82.44183974312955,98.24319236056272],[70.41907144725656,93.09057737661715],[47.4040578522995,77.28922475918398],[17.518890945415023,48.778088514684896],[-1.374030662385394,19.92344460458935],[-3.09156899036725,2.748061324770788]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"E-ZdZj8UtlRsvoouszYUd","type":"line","x":-3072.989880947711,"y":-3760.0717372754575,"width":12.444113076398935,"height":9.028082035818898,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":585917497,"version":341,"versionNonce":1332531206,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[0.7320066515526378,7.320066515529106],[10.736097556109144,9.028082035818898],[12.444113076398935,2.440022171842884]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"d6rEVT30i8n901djdOpul","type":"line","x":-3051.7616880526775,"y":-3751.6895212787063,"width":16.86461511711377,"height":10.714468125701387,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1224191447,"version":495,"versionNonce":1183619930,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[1.952017737474307,10.248093121741022],[13.743054964670137,10.714468125701387],[16.86461511711377,5.76991259993747]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"e2upTWTOMtHh0zoCYF1OP","type":"line","x":-2983.441067241074,"y":-3720.5433780916014,"width":12.932117510767512,"height":11.468104207662236,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":48595577,"version":516,"versionNonce":715185990,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[0.7320066515530925,10.248093121741022],[9.272084253003413,11.468104207662236],[12.932117510767512,4.14803769213313]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"-CmNQa2zGA6fZXwBw5GDj","type":"line","x":-2910.240402085785,"y":-3696.8751630247243,"width":13.420121945136543,"height":12.44411307639939,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1242615897,"version":560,"versionNonce":1943281690,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[1.708015520290246,10.98009977329366],[9.272084253003413,12.44411307639939],[13.420121945136543,4.14803769213313]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"e3cPNDNdYhx7QpKSYTJIN","type":"line","x":-2880.960136023669,"y":-3692.9711275497752,"width":14.152128596689636,"height":7.564068732713622,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1540166425,"version":621,"versionNonce":2064713350,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[3.416031040580492,7.076064298345045],[11.712106424846297,7.564068732713622],[14.152128596689636,0.48800443436857677]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"G929eC4DpEMpzeFBMhHJe","type":"line","x":-2840.9437724054437,"y":-3699.803189630936,"width":12.932117510767966,"height":9.516086470187929,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1679986649,"version":627,"versionNonce":1062014170,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[0.9760088687371535,6.5880598639764685],[9.028082035818898,4.880044343686222],[12.932117510767966,-2.9280266062114606]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"ODnViACzxc7P8sd7C6xzK","type":"line","x":-2967.7104677673183,"y":-3818.6198702516685,"width":47.382928908961276,"height":10.5295397575469,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1505877753,"version":451,"versionNonce":1903838662,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[17.832285073264757,-8.151901747778084],[37.1930517242381,-8.151901747778084],[46.533772476900594,-1.8681441505323164],[42.79748417583551,0.8491564320602265],[27.17300582592725,-5.434601165185541],[13.07700905372758,-2.887131869004861],[2.717300582592543,2.377638009768816],[-0.8491564320606813,0.33966257282418155]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"H6rVoPCHdCWMUha4t6g1G","type":"line","x":-2961.426710170073,"y":-3805.7126924843524,"width":36.853389151414376,"height":32.60760699111279,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1680190777,"version":407,"versionNonce":780820890,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[6.283757597245767,6.793251456481812],[16.303803495556622,-8.661395607014128],[27.852330971576066,-18.341778932501256],[36.853389151414376,-20.37975436944589],[30.90929412699279,-25.814355534630977],[19.870260510209846,-20.889248228681936],[6.113926310833904,-9.170889466250628],[0,0]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"WhFE5hmA4drx2zV-ml-ZQ","type":"line","x":-2945.6946485434114,"y":-3802.992025534668,"width":37.82251291275588,"height":10.286892248249842,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1117395351,"version":405,"versionNonce":519675142,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[2.909424070212026,5.19540012537891],[17.664360426287203,-0.5195400125376182],[37.82251291275588,3.74068809027267],[33.25056080242257,-2.701608065196524],[18.495624446347847,-5.091492122870932],[0,0]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"86tqv7q5kgZeyiHaapFi7","type":"line","x":-2944.551660515828,"y":-3786.574561138472,"width":32.9388367949,"height":31.068492749763664,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":2052162647,"version":421,"versionNonce":482287194,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[5.611032135409005,4.571952110332859],[11.22206427081801,-8.624364208128554],[19.84642847894611,-15.794016381150868],[31.795848767316784,-22.963668554173182],[26.496540639430805,-26.496540639430805],[12.572868303416271,-19.534704471423538],[3.636780087765146,-7.169652173022314],[-1.1429880275832147,0.20781600501504727]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"xb6kvyO4nG67KuY5RR5hs","type":"line","x":-2925.7443120619573,"y":-3785.1198491033656,"width":38.134236920278454,"height":7.689192185560387,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":2068103161,"version":461,"versionNonce":1762397254,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[13.300224320968937,-4.364136105318266],[34.28964082749826,-2.078160050151382],[36.78343288768019,2.389884057673953],[21.19723251154437,-0.20781600501504727],[3.0133320727195496,3.3250560802421205],[-1.350804032598262,-0.20781600501504727]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"5eSOiwmw_ZqfD368TmcLB","type":"line","x":-2927.3029320995706,"y":-3770.988360762336,"width":29.405964709642376,"height":28.886424697105213,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":322599865,"version":463,"versionNonce":113132314,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[6.130572147946623,4.779768115348361],[17.352636418764178,-13.81976433350701],[29.405964709642376,-18.91125645637794],[25.769184621877685,-24.10665658175685],[12.468960300907838,-20.15815248646868],[4.779768115347906,-10.49470825326489],[0,0]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"t0HygINl--ggQt2eGNDTs","type":"line","x":-2985.2590644480756,"y":-3880.9311192579435,"width":32.325375115022325,"height":35.26404558002423,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#2b8a3e","fillStyle":"cross-hatch","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":948407321,"version":654,"versionNonce":2106495878,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[10.635188349530836,15.952782524297163],[17.35214941239292,29.946451405259268],[30.086388094068298,24.48892054168391],[25.468477363350758,17.492086101202858],[17.35214941239292,-5.317594174764963],[5.7374042411943265,-4.757847419527025],[-2.2389870209540277,-1.1194935104767865]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"PmzIxr4MqAN2CVq9FvPxD","type":"line","x":-3001.0857754202084,"y":-3840.4919914775764,"width":77.78272917671757,"height":21.39874208791798,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1167041591,"version":493,"versionNonce":1459277786,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[6.113926310833904,5.434601165185541],[25.644524248219113,-4.075950873889269],[48.2320853410215,-4.2457821603011325],[71.66880286588412,4.415613446712996],[77.78272917671757,10.5295397575469],[67.59285199199485,-4.415613446713451],[47.89242276819732,-10.5295397575469],[27.512668398751885,-10.869202330371081],[1.3586502912962715,-0.1698312864118634]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null},{"id":"bV0Y3b9_m3B-vVDEFWgvL","type":"line","x":-2984.74124403951,"y":-3823.336724968013,"width":46.533772476900594,"height":38.04220815629833,"angle":0,"strokeColor":"#2b8a3e","backgroundColor":"#d5e1d9","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":["bcG19vkApGTfzWO2m0soY"],"roundness":{"type":2},"seed":1059604343,"version":486,"versionNonce":1186869958,"isDeleted":false,"boundElements":null,"updated":1682008206995,"link":null,"locked":false,"points":[[0,0],[5.094938592361359,5.2647698787732224],[15.794309636320122,-14.095996772200124],[32.77743827752511,-26.323849393867476],[46.533772476900594,-28.531656117223974],[43.30697803507201,-32.77743827752511],[26.833343253103067,-30.90929412699279],[13.756334199375488,-19.360766650973346],[0,0]],"lastCommittedPoint":null,"startBinding":null,"endBinding":null,"startArrowhead":null,"endArrowhead":null}],"files":{}}
```

**Comment by PFound** [comment]
@dwelle Looks good, maybe too detailed for the library.

**Comment by PFound** [comment]
Now you have put it next to it, your right! 

Happy for that to be in there, unsure how to go about updating the library though.

**Comment by dwelle** [comment]
replaced by https://github.com/excalidraw/excalidraw-libraries/pull/939

**Pull request closed without merging**
