### PR TITLE
feat: new library Flow Chart Symbols

### PR DESCRIPTION
**Pull request by excalibot**
Common symbols used in flow chart, including: Start / End, Process, Decision, Document, Multiple Document, Manaual Input, 
Predefined Process, Input / Output, And, Or, Database, Preparation / Initialization, 
Delay, Connector, Off-page Connector

Submitted by @finfin

Items: Off-page Connector, Connector, Delay, Preparation / Initialization, Database, Or, And, Input / Output, Predefined Process, Manaual Input, Multiple Document, Document, Decision, Process, Start / End

[Installation link](https://excalidraw.com/?addLibrary=https%3A%2F%2Fraw.githubusercontent.com%2Fexcalidraw%2Fexcalidraw-libraries%2Ffinfin-flow-chart-symbols-1717806157297%2Flibraries%2Ffinfin%2Fflow-chart-symbols.excalidrawlib%3Fraw%3Dtrue)

### CODE REVIEW

**Comment by finfin** [comment]
Some more infos:

I love using excalidraw to draw all kinds of diagrams. Among these diagrams, flow chart is the most common diagram used in software development / product development. 

But the lack of flow chart symbols in excalidraw library made the diagram creation process less then ideal. So I created these symbols myself.

And I'm sure these will help many of those who uses excalidraw to draw diagrams. Since it's a very common diagram.

**Comment by finfin** [comment]
Some more infos:

I love using excalidraw to draw all kinds of diagrams. Among these diagrams, flow chart is the most common diagram used in software development / product development.

But the lack of flow chart symbols in excalidraw library made the diagram creation process less then ideal. So I created these symbols myself.

And I'm sure these will help many of those who uses excalidraw to draw diagrams. Since it's a very common diagram.

@dwelle would love some feedbacks

**Comment by finfin** [comment]
Some more infos:

I love using excalidraw to draw all kinds of diagrams. Among these diagrams, flow chart is the most common diagram used in software development / product development.

But the lack of flow chart symbols in excalidraw library made the diagram creation process less then ideal. So I created these symbols myself.

And I'm sure these will help many of those who uses excalidraw to draw diagrams. Since it's a very common diagram.

@dwelle would love some feedbacks

**Comment by dwelle** [comment]
Merging, thanks!

**Pull request merged**
