### PR TITLE
Add dropdowns library

### PR DESCRIPTION
**Pull request by h7y**

### CODE REVIEW

**Comment by dwelle** [comment]
It looks like the items are duplicated? Only three are unique.

**Comment by h7y** [comment]
I was trying to implement a split button dropdown ([example](https://getbootstrap.com/docs/5.0/components/dropdowns/#split-button)). I noticed that I didn't align the items properly, fixed it now! 

If the split button dropdown seems insignificant, let me know, I'll remove it :)

**Comment by lipis** [comment]
Can we remove the last 3. They are not that common.

**Comment by h7y** [comment]
Removed it, @lipis 👍🏽

**Pull request merged**
