### PR TITLE
feat scrum board

### PR DESCRIPTION
**Pull request by danimaniarqsoft**
This is a **scrum board** with statuses and cards that are commonly used in the **scrum methodology** for agile software developments

### CODE REVIEW

**Comment by dwelle** [comment]
Hey. What's the idea of how this will be used? Should the sticky notes in the example scrum board be used for writing on?

Also, let's group the bug elements (select all the bug, and press `Cmd/ctrl+G`) for easier manipulation.

**Comment by ferminrp** [comment]
I think if we group the bug we are good to merge. Nice addition!

**Comment by danimaniarqsoft** [comment]
I have grouped the bugs elements, so that they can be easier to manipulate, I look forward to hearing your comments, thanks!!

**Comment by ferminrp** [comment]
Thanks! Merging

**Review by ferminrp — APPROVED** [review]

**Pull request merged**
