### PR TITLE
#58 add sort by

### PR DESCRIPTION
**Pull request by nrgapple**

### CODE REVIEW

**Comment by nrgapple** [comment]
This pr is for issue #58

**Comment by dwelle** [comment]
Hey! Thanks for the PR.

Can we make it so that it doesn't refresh the page? And also add an active class for current sort type?

Maybe it's time we migrate to CRA @lipis

**Comment by nrgapple** [comment]
sure. I was just following the patterns already in place. I could convert it to a nextjs typescript site pretty quickly

**Comment by dwelle** [comment]
Not sure about Next.js since long-term we wanna make this a full-blown app. But let's leave that for another discussion.

**Comment by nrgapple** [comment]
got it. what did you mean by an _active class for current sort type_?

**Comment by lipis** [comment]
> got it. what did you mean by an _active class for current sort type_?

Maybe something like different color or something..

This looks great for what it is right now.. and as for a fully fledged app I would also go with CRA as we already using it..

I'll write down the requirements somewhere as we would like to keep getting the data from Analytics to avoid dealing with it ourselves and GH actions working perfectly for that.

**Comment by lipis** [comment]
This looks great btw!

**Comment by nrgapple** [comment]
Ok I'll add some way to know which sort is selected

**Comment by lipis** [comment]
I like it.. let's keep it for now!

**Pull request merged**
