### PR TITLE
feat: new library daatha

### PR DESCRIPTION
**Pull request by excalibot**
Data sources, protocols, apis, and sinks - USB, email, FTP, kafka, GraphQL, databases, RESTful interfaces 

Submitted by @kvchitrapu

Items: USB, email, FTP, data sources

[Installation link](https://excalidraw.com/?addLibrary=https%3A%2F%2Fraw.githubusercontent.com%2Fexcalidraw%2Fexcalidraw-libraries%2Fkvchitrapu-daatha%2Flibraries%2Fkvchitrapu%2Fdaatha.excalidrawlib%3Fraw%3Dtrue)

### CODE REVIEW

**Comment by kvchitrapu** [comment]
Please merge

**Comment by dwelle** [comment]
@kvchitrapu the mail and FTP items aren't grouped. Could you group them and update the lib?

**Comment by kvchitrapu** [comment]
@dwelle , the [excalidraw](https://excalidraw.com/) publish library allows only new items. What is the process to update? Should I commit straight to git. Please point me to documentation on updates.

**Comment by dwelle** [comment]
sorry @kvchitrapu, I missed you reply. Yes, the flow right now is not good. You either need to manually update the PR (which you can't in this case since it was made by @excalibot) or just re-publish the lib (you'd need to re-add the items to the library for them to appear as unpublished). We need to improve.

Anyway, this one's one me so I made the changes and republished https://github.com/excalidraw/excalidraw-libraries/pull/361

**Pull request closed without merging**
