### PR TITLE
add azure cloud services library

### PR DESCRIPTION
**Pull request by YouriTjang**
Icons for some azure cloud services. 
Note, I decided to keep the descriptions below the icons ('Subscription', 'Resource Group', etc), because azures icons are not always clear to me without that description.

### CODE REVIEW

**Comment by YouriTjang** [comment]
Is there a way to see what fails the build? When I click the vercel link, I get a 404

**Comment by dwelle** [comment]
Hey. It seems that the actions weren't running for a few days due to an auth issue, and then the stats.py script fell behind and now it expects some files that weren't build previously or something. Haven't dug deep. Will try to figure out later (I haven't written any of it).

```
08:04:09.362 | yarn run v1.22.10
08:04:09.389 | $ yarn build:key &amp;&amp; yarn build:stats &amp;&amp; yarn format
08:04:09.598 | $ python3 key.py
08:04:09.842 | $ python3 stats.py
08:04:10.241 | Traceback (most recent call last):
08:04:10.241 | File "stats.py", line 156, in &lt;module&gt;
08:04:10.241 | main()
08:04:10.242 | File "stats.py", line 114, in main
08:04:10.242 | with open(libraries_file, "r") as day_totals:
08:04:10.242 | FileNotFoundError: [Errno 2] No such file or directory: '/vercel/path0/stats/2021-05-15.json'
08:04:10.285 | error Command failed with exit code 1.
08:04:10.285 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
08:04:10.302 | error Command failed with exit code 1.
08:04:10.302 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
08:04:10.317 | Error: Command "yarn run build" exited with 1
```

**Comment by YouriTjang** [comment]
Alright, thanks!

**Comment by dwelle** [comment]
@YouriTjang can you try to merge with `main` to see if it fixes the deployment?

**Comment by YouriTjang** [comment]
@dwelle Cool, that works :)

**Comment by dwelle** [comment]
I've attempted to clean up the commit tree. If everything looks ok, we can merge!

**Comment by YouriTjang** [comment]
thanks for the cleanup. All looks good to me

**Pull request merged**
