### PR TITLE
A collection of icons used for design documents including NSX-T VMware components

### PR DESCRIPTION
**Pull request by novakkkarel**

### CODE REVIEW

**Comment by ad1992** [comment]
@novakkkarel are you facing some issue in creating PR for adding a new library? as there are a [couple of PR's](https://github.com/excalidraw/excalidraw-libraries/pulls?q=is%3Apr+author%3Anovakkkarel) opened and closed by you

**Comment by novakkkarel** [comment]
Yes I have problem but last version is I hope good can you double check
please … thanks

On 16 June 2021 at 10:20:55, Aakansha Doshi ***@***.***)
wrote:

@novakkkarel <https://github.com/novakkkarel> are you facing some issue in
creating PR for adding a new library? as there are a couple of PR's
<https://github.com/excalidraw/excalidraw-libraries/pulls?q=is%3Apr+author%3Anovakkkarel>
opened and closed by you

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/excalidraw/excalidraw-libraries/pull/139#issuecomment-862157342>,
or unsubscribe

**Comment by ad1992** [comment]
@novakkkarel you will need to add the `excalidrawLib` and `png` file as well as mentioned [here](https://github.com/excalidraw/excalidraw-libraries#add-your-own-library-to-the-list) then it will be listed in [libraries.excalidraw.com](libraries.excalidraw.com)

**Comment by novakkkarel** [comment]
Hi I uploaded , if is not problem can you upload please thanks


On 16 June 2021 at 21:31:09, Aakansha Doshi ***@***.***)
wrote:

@novakkkarel <https://github.com/novakkkarel> you will need to add the
excalidrawLib and png file as well as mentioned here
<https://github.com/excalidraw/excalidraw-libraries#add-your-own-library-to-the-list>
then it will be listed in libraries.excalidraw.com

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/excalidraw/excalidraw-libraries/pull/139#issuecomment-862655597>,
or unsubscribe

**Comment by ad1992** [comment]
> Hi I uploaded, it is not a problem can you upload please thanks


@novakkkarel could you share your files here? you can just drag and drop the files here and it should work or could you confirm if the files added in https://github.com/excalidraw/excalidraw-libraries/pull/141/files are correct? then we will merge the changes there

**Comment by novakkkarel** [comment]
Yes are correct thanks

-- 
Karel Novak

**Comment by novakkkarel** [comment]
Hi I still dont see in libraries .. do you need still something? Thank you


On 16 June 2021 at 22:23:41, Aakansha Doshi ***@***.***)
wrote:

Hi I uploaded, it is not a problem can you upload please thanks

@novakkkarel <https://github.com/novakkkarel> could you share your files
here? you can just drag and drop the files here and it should work or could
you confirm if the files added in
https://github.com/excalidraw/excalidraw-libraries/pull/141/files are
correct? then we will merge the changes there

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/excalidraw/excalidraw-libraries/pull/139#issuecomment-862694697>,
or unsubscribe

**Comment by ad1992** [comment]
@novakkkarel sorry forgot about this , lemme do it now

**Comment by ad1992** [comment]
closing this as I am updating https://github.com/excalidraw/excalidraw-libraries/pull/141

**Pull request closed without merging**
