### PR TITLE
Add Library: Team Topologies

### PR DESCRIPTION
**Pull request by crubier**
Added Primitives to create Team Topologies Diagrams, as per Matthew Skelton and Manuel Pais.

### CODE REVIEW

**Comment by crubier** [comment]
It allows to create diagrams that looks like this

Screenshot 2021-02-08 at 15 16 54

And the primitives are these:

Screenshot 2021-02-08 at 15 16 58

**Comment by YouriTjang** [comment]
Nice, I've already started using your library.
I'd prefer the other models for the interaction-modes though:
image

**Comment by ferminrp** [comment]
Hey 👋 

How is this different from the one @VLecrubier built

image

**Comment by crubier** [comment]
@ferminrp I am @VLecrubier, same person 🖖 

But @nikordaris an improved version since ( https://github.com/excalidraw/excalidraw-libraries/pull/105 ), which conforms better to the Team Topologies website, as @YouriTjang mentioned, so all good.

**Pull request closed without merging**
