### PR TITLE
Added Firebase, GoogleDrive, Kanoma, Lobe.AI and Flutter

### PR DESCRIPTION
**Pull request by pclainchard**
I've just updated my library with new Logos and an updated version of the one from my company :)

### CODE REVIEW

**Comment by dwelle** [comment]
Awesome, thanks!

**Comment by dwelle** [comment]
Can you also add the new logos to the description so it's searchable?

**Comment by pclainchard** [comment]
Yup, I'll do it tomorrow morning :)

**Comment by dwelle** [comment]
Merging!

**Comment by pclainchard** [comment]
I made a mistake in my PR ... the last 3 icons are missing, should I create a new one or can this PR be reopened ?

**Comment by dwelle** [comment]
@pclainchard no problem. But yes, you'll have create a new PR.

**Pull request merged**
