### PR TITLE
Adding System Design Components

### PR DESCRIPTION
**Pull request by himz**
Adding System Design Components

Why
- Need to have some readily used components for system design. 

How
- Added components like Load Balancer, CDN, User, DB, Read replicas, Table etc.

### CODE REVIEW

**Comment by nrgapple** [comment]
Very cool. Its functional in its current state but maybe some colors could be helpful?

**Comment by himz** [comment]
> 
> 
> Very cool. Its functional in its current state but maybe some colors could be helpful?

Thanks. I do have that in mind, esp. for use cases like caches. 
Main idea was to have wire frame components which can be connected easily via arrows. (Check db, the vertical lines are actually circle, for each arrow connection), for quick mockup of the system. 

planning to expand further as i get more time.

**Review by nrgapple — APPROVED** [review]

**Comment by himz** [comment]
The MR is approved. Can I get help with merging this in ?

**Comment by ferminrp** [comment]
Agree with nrgapple, this feels like it can be done by anyone very fast. Perhaps adding some more love to it?

For example the read replica label doesnt event fit the icon
image

**Pull request closed without merging**
