### PR TITLE
feat: new library Nextflow - Seqera - nf-core

### PR DESCRIPTION
**Pull request by excalibot**
Logos for Seqera and it's products (Nextflow, MultiQC, Wave, Fusion).
Logo for nf-core, and components for drawing diagrams and metro maps.

Submitted by @ewels

Items: Stations - 3, Stations - 2, VCF - multiple, BAM - multiple, FastQ - multiple, VCF file, BAM file, FastQ file, nf-core logo, Fusion logo, Wave logo, Seqera logo, MultiQC logo, Nextflow logo

[Installation link](https://excalidraw.com/?addLibrary=https%3A%2F%2Fraw.githubusercontent.com%2Fexcalidraw%2Fexcalidraw-libraries%2Fewels-nextflow-seqera-nf-core-1726690352631%2Flibraries%2Fewels%2Fnextflow-seqera-nf-core.excalidrawlib%3Fraw%3Dtrue)

### CODE REVIEW

**Comment by ewels** [comment]
Hi folks! Whilst I'm here, thought I should note that I struggled to submit this. In the developer console I was getting a bunch of CORS errors, and one time I got this error:



I couldn't get the form to submit in either Chrome or Firefox (MacOS). In the end I got it to work by using a [Chrome plugin](https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en-GB&utm_source=ext_sidebar) to disable CORS. Made it! ⚔️ 🙌🏻 

Many thanks for your consideration anyway 🙏🏻

**Comment by kenibrewer** [comment]
@dwelle Wanted to flag this review and possible merging. nf-core is an organization of over 10,000 open-source bioinformatics developers that collaborate on scientific data pipelines. The icons in this library pack are components that would let us use Excalidraw for the metromaps we use. 

As an aside @ewels also ran a [training](https://youtu.be/GGwGZOulD8A?si=N0d_L2oajeKIaDIU) in our weekly sharing meeting about Excalidraw so we're very excited about it.

**Comment by sateeshperi** [comment]
this will make drawing pipeline metro-maps easy!

**Comment by ewels** [comment]
For context - these tools are used when building open-source scientific / clinical data analysis pipelines. Our community like to draw "metro maps" to visualise how a given pipeline works (see our [guidelines](https://nf-co.re/docs/guidelines/graphic_design#workflow-schematics)).

I recently [gave a talk](https://nf-co.re/events/2024/bytesize_excalidraw) about Excalidraw and now a lot of people are excited to start using it 🤩

**Comment by maxulysse** [comment]
I so want this <3

**Comment by apeltzer** [comment]
Same here!

**Comment by ewels** [comment]
Brilliant stuff, thank you!

**Pull request merged**
