### PR TITLE
Add random figure drawings

### PR DESCRIPTION
**Pull request by Vasudevatirupathinaidu**
Adding few figure drawings for logos, icons, and a pictorial representation for HTML, CSS & JS.

### CODE REVIEW

**Comment by Vasudevatirupathinaidu** [comment]
Can anyone have a look at this, please?

**Comment by ad1992** [comment]
@Vasudevatirupathinaidu thanks for the contribution :) 
Where do you think the pictorial representation would be useful?

**Comment by Vasudevatirupathinaidu** [comment]
@ad1992 thank you for the prompt reply Aakansha :)
The pictorial representation is useful for the presentation (for example PowerPoint ). It is helpful for beginners to understand the tools and how they can fit for creating the products. These are just templates. So, the text can be changed to anything else to make these templates much more useful.

**Comment by dwelle** [comment]
I think the pictorial representation doesn't seem a good fit for the types of libraries we publish here. In my opinion, everyone will want to draw themselves similar diagrams to specifically address their needs and presentations.

The figures are good. If you remove the pictorial representations and keep the figures, we can publish!

**Comment by Vasudevatirupathinaidu** [comment]
@dwelle Thank you for the clarification, David! I will remove the pictorial representations.

**Comment by dwelle** [comment]
I'd suggest putting white-background shapes underneath each layer of the striped-background shapes for better legibility:

https://excalidraw.com/?#json=5740914815270912,tk6GtRdNlIFZxF0sB-SAcA

image

**Comment by Vasudevatirupathinaidu** [comment]
Yes! you are right. I will modify that. Thank you for your suggestion @dwelle

**Comment by Vasudevatirupathinaidu** [comment]
@dwelle Hello David, I have updated.

**Review by ad1992 — APPROVED** [review]

**Comment by dwelle** [comment]
@Vasudevatirupathinaidu it seems all the figures are a single library item now. Was that intentional?

**Comment by Vasudevatirupathinaidu** [comment]
Yes, David. That was intentional.

**Comment by dwelle** [comment]
Can we split them again? You'll likely want to insert just a single character, not all at once (and the accessories on top).

Later, we're also planning to support installing individual library items and this would prevent that as well.

**Comment by Vasudevatirupathinaidu** [comment]
Hello @dwelle, I just updated that. Please check and let me know.

**Comment by dwelle** [comment]
Looks good, thanks!

**Comment by Vasudevatirupathinaidu** [comment]
Thank you @dwelle @ad1992

**Pull request merged**
